import billing_payment              #importing the file billing_payment
import random
randomNum=random.randint(1,100)
file = open("INV-"+str(randomNum)+".txt", 'w')  
file.write("Bill Number                             : ") 
file.write(str(randomNum)) 
file.write("\n")  
file.write("Enter the Customer Name                 : ")
file.write(billing_payment.name)
file.write("\n")
file.write("Enter the Phone Number-1                : ")
file.write(str(billing_payment.phn_no_1))
file.write("\n")
file.write("Enter the Phone Number-2                : ")
file.write(str(billing_payment.phn_no_2))
file.write("\n")
file.write("Enter the Address of the Customer       : ")
file.write(billing_payment.address)
file.write("\n")
file.write("Enter the Date of Order                 : ")
file.write(billing_payment.date_of_order)
file.write("\n")
file.write("Enter the Date of Goods to be Delivered : ")
file.write(billing_payment.delivery_date)
file.write("\n")
file.write("Enter the Delivery Time                 : ")
file.write(billing_payment.delivery_time)
file.write("\n")
file.write("Total Cost of Sweet                     : ")
file.write(str(billing_payment.total_cost_Sweet))
file.write("\n")
file.write("Total Cost of Savouries                 : ")
file.write(str(billing_payment.total_cost))
file.write("\n")
file.write("Total Amount                            : ")
file.write(str(billing_payment.whole_amount))
file.write("\n")
file.write("Amount paid in Advance                  : ")
file.write(str(billing_payment.paid))
file.write("\n")
file.write("Door Delivery                           : ")
file.write(billing_payment.ch)
file.write("\n")
if billing_payment.ch=='yes':
    file.write("Door Delivery Address                   : ")
    file.write(billing_payment.dd_address)
file.write("\n")
file.write("Packaging Details                       : ")
file.write(str(billing_payment.packaging_details))
file.write("\n")
file.write("Balance                                 : ")
file.write(str(billing_payment.balance))
file.write("\n")
file.write("Payment Type                            : ")
file.write(str(billing_payment.payment_type))
if billing_payment.payment_type=='upi':
    file.write("\n")
    file.write("Transaction Id                          : ")
    file.write(str(billing_payment.transaction_id))
file.close()    #closing the file

