# Generated by Django 5.1.7 on 2025-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank="False", max_length=15)),
                ("name", models.CharField(blank="False", max_length=30)),
                ("pricePerGram", models.FloatField()),
                ("pricePerPiece", models.FloatField()),
                ("availableQtyGrams", models.FloatField()),
                ("availableQtyPieces", models.IntegerField()),
            ],
            options={"verbose_name_plural": "Inventory",},
        ),
    ]
