# Generated by Django 5.1.7 on 2025-04-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventorymngmt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="availableQtyGrams",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="availableQtyPieces",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="pricePerGram",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="pricePerPiece",
            field=models.FloatField(null=True),
        ),
    ]
