# Generated by Django 5.1.7 on 2025-04-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billno", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
                ("mobile", models.IntegerField(unique=True)),
                ("address", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
                ("pincode", models.IntegerField()),
                ("order_date", models.IntegerField()),
                ("delivery_date", models.IntegerField()),
                ("sweets", models.CharField(max_length=50)),
                ("sweet_pieces", models.IntegerField()),
                ("savouries", models.CharField(max_length=50)),
                ("savouries_gram", models.IntegerField()),
                ("paymenttype", models.CharField(max_length=20)),
                ("amount", models.IntegerField()),
                ("advance", models.IntegerField()),
                ("packaging_detail", models.CharField(max_length=50)),
            ],
        ),
    ]
