# Generated by Django 5.1.7 on 2025-04-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("mobile", models.IntegerField(unique=True)),
                ("address", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
                ("pincode", models.IntegerField()),
            ],
        ),
    ]
